// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	ws "chatim/service/platform/internal/handler/ws"
	"chatim/service/platform/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/mtflower",
				Handler: ws.MtflowerWsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/elmflower",
				Handler: ws.ElmflowerWsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: ws.WsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/platform/ws"),
	)
}
