// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcerrordetails.proto

package grpcerrordetails

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcErrorDetails struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcErrorDetails) Reset()         { *m = GrpcErrorDetails{} }
func (m *GrpcErrorDetails) String() string { return proto.CompactTextString(m) }
func (*GrpcErrorDetails) ProtoMessage()    {}
func (*GrpcErrorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_de48da0f9d812447, []int{0}
}

func (m *GrpcErrorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcErrorDetails.Unmarshal(m, b)
}
func (m *GrpcErrorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcErrorDetails.Marshal(b, m, deterministic)
}
func (m *GrpcErrorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcErrorDetails.Merge(m, src)
}
func (m *GrpcErrorDetails) XXX_Size() int {
	return xxx_messageInfo_GrpcErrorDetails.Size(m)
}
func (m *GrpcErrorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcErrorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcErrorDetails proto.InternalMessageInfo

func (m *GrpcErrorDetails) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GrpcErrorDetails) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*GrpcErrorDetails)(nil), "grpcerrordetails.GrpcErrorDetails")
}

func init() { proto.RegisterFile("grpcerrordetails.proto", fileDescriptor_de48da0f9d812447) }

var fileDescriptor_de48da0f9d812447 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2f, 0x2a, 0x48,
	0x4e, 0x2d, 0x2a, 0xca, 0x2f, 0x4a, 0x49, 0x2d, 0x49, 0xcc, 0xcc, 0x29, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x40, 0x17, 0x57, 0xb2, 0xe2, 0x12, 0x70, 0x2f, 0x2a, 0x48, 0x76, 0x05,
	0x89, 0xb9, 0x40, 0xc4, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0xc0, 0x6c, 0x90, 0x58, 0x4a, 0x6a, 0x71, 0xb2, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x98, 0x9d, 0xc4, 0x06, 0x36, 0xd4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x55, 0xb0,
	0x32, 0x60, 0x6e, 0x00, 0x00, 0x00,
}
